In [1]:
#question 1

import pandas as pd

print(pd.__version__)

1.4.2


In [2]:
#question 2

import wget
import os

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
download_path = "Downloads/"
output_file = os.path.join(download_path, "housing.csv")

wget.download(url, out=output_file)

df = pd.read_csv(output_file)

# Get number of columns
num_columns = df.shape[1]  # 2nd element represents the number of columns

print("Number of columns:", num_columns)


 60% [................................                      ]  868352 / 1423529

100% [......................................................] 1423529 / 1423529Number of columns: 10


In [3]:
#question 3

# Check for missing values in each column
missing_values = df.isnull().sum()

# Print number of missing values in each column
print(missing_values)


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


In [4]:
#question 4

# Calculate number of unique values for each column
unique_values_counts = df.nunique()

print("Number of unique values for each column:")
print(unique_values_counts)

Number of unique values for each column:
longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64


In [5]:
#question 5

# Count the number of instances in ocean_proximity with value "NEAR BAY"
count_near_bay = (df['ocean_proximity'] == 'NEAR BAY').sum()

print("Number of instances with value 'NEAR BAY':", count_near_bay)

Number of instances with value 'NEAR BAY': 2290


In [6]:
# Select the 'median_house_value' for rows where ocean_proximity is 'NEAR BAY'
median_house_value_near_bay = df.loc[df['ocean_proximity'] == 'NEAR BAY', 'median_house_value']

print("median_house_value for rows with ocean_proximity 'NEAR BAY':")
print(median_house_value_near_bay)

median_house_value for rows with ocean_proximity 'NEAR BAY':
0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
19067    297600.0
19068    208000.0
19069    262300.0
19077    213200.0
19104    246300.0
Name: median_house_value, Length: 2290, dtype: float64


In [7]:
# Calculate the average of 'median_house_value' for these rows
mean_median_house_value_near_bay = median_house_value_near_bay.mean()

print("Average of median_house_value for rows with ocean_proximity 'NEAR BAY':", mean_median_house_value_near_bay)

Average of median_house_value for rows with ocean_proximity 'NEAR BAY': 259212.31179039303


In [8]:
#question 6.1

# Calculate the average of the 'total_bedrooms' column
mean_total_bedrooms = df['total_bedrooms'].mean()

mean_total_bedrooms = round(mean_total_bedrooms, 3) 

print("Average of total_bedrooms column:", mean_total_bedrooms)


Average of total_bedrooms column: 537.871


In [9]:
#question 6.2

# Fill missing values in 'total_bedrooms' with the mean value
df['total_bedrooms'].fillna(mean_total_bedrooms, inplace=True)

# Check if there are any remaining missing values
missing_values_after_fillna = df['total_bedrooms'].isnull().sum()

print("Mean value for 'total_bedrooms' used for filling missing values:", mean_total_bedrooms)
print("Number of remaining missing values in 'total_bedrooms' after filling:", missing_values_after_fillna)

Mean value for 'total_bedrooms' used for filling missing values: 537.871
Number of remaining missing values in 'total_bedrooms' after filling: 0


In [10]:
#question 6.3

# Calculate the average of the 'total_bedrooms' column
mean_total_bedrooms = df['total_bedrooms'].mean()

mean_total_bedrooms = round(mean_total_bedrooms, 3) 
print("Average of total_bedrooms column:", mean_total_bedrooms)

Average of total_bedrooms column: 537.871


In [11]:
#question 7.1
on_islands = df.loc[df['ocean_proximity'] == 'ISLAND']
print(on_islands)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

In [12]:
#question 7.2

# Select the 'housing_median_age', 'total_rooms', 'total_bedrooms' for rows where ocean_proximity is 'ISLAND'
selected_data = df.loc[df['ocean_proximity'] == 'ISLAND', ['housing_median_age', 'total_rooms', 'total_bedrooms']]
print(selected_data )

      housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0


In [13]:
#question 7.3

import numpy as np

# Convert to a NumPy array
X = np.array(selected_data)

print("X:")
print(X)

X:
[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [14]:
#question 7.4 Part A

XT = X.T

print("X:")
print(X)
print("\nX Transpose:")
print(XT)

X:
[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]

X Transpose:
[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]


In [15]:
#question 7.4 Part B

#Compute matrix-matrix multiplication between the transpose of X and X.

# Perform matrix-matrix multiplication
XTX = np.dot(XT, X)

# Print the result
print("Result:")
print(XTX)

Result:
[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [16]:
#question 7.5

# Check if the matrix is square (i.e., number of rows = number of columns)
if XTX.shape[0] == XTX.shape[1]:
    # Compute the inverse of the matrix
    inverse_XTX = np.linalg.inv(XTX)
    
    # Print the inverse matrix
    print("XTX:")
    print(XTX)
    print("\nInverse XTX:")
    print(inverse_XTX)
else:
    print("The matrix is not square. Cannot compute inverse.")

XTX:
[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]

Inverse XTX:
[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [17]:
#question 7.6

y = np.array([950, 1300, 800, 1000, 1300])

# Print the NumPy array y
print("y:", y)

y: [ 950 1300  800 1000 1300]


In [18]:
#question 7.7

result_dot = np.dot(inverse_XTX,XT)

print(result_dot)

w = np.dot(result_dot,y)

print("w:")
print(w)

[[-0.00825608 -0.00653208 -0.00232159  0.02565144  0.01204934]
 [-0.00165852  0.0011141   0.00139656 -0.00103215 -0.00110698]
 [ 0.00754365 -0.00301964 -0.00455125  0.00181685  0.00329418]]
w:
[23.12330961 -1.48124183  5.69922946]
